spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 113011
    url: jdbc:mariadb://localhost:3306/be_project_1st

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
